### ISSUE TITLE
「便宜」在shupin.dict.yaml裡面，但是蜀拼重慶用pian li打不出來

### ISSUE THREAD

**Issue by AlienKevin** [Papnas/shupin#12]
要手動選擇用讀音pian和li分別選中「便」和「宜」之後，才可以組詞「便宜」。

另一個相關問題：
順便查了一下1900年出版的[《西蜀方言》](https://github.com/Papnas/Bibliotheca-Amridica/blob/master/%E8%A5%BF%E8%9C%80%E6%96%B9%E8%A8%80.pdf)，裡面「便」在組詞「便宜」時讀p'ien2，和dict.yaml一樣

![便](https://user-images.githubusercontent.com/22850071/164031031-4aa2f22a-1c1e-41d5-971b-32902fb4b752.png)

但是《西蜀方言》說「宜」是讀ngi2。看到dict.yaml裡面卻說是讀ni2。[這篇文章](https://zhuanlan.zhihu.com/p/34562639)說「(四川話通用拼音)这个方案不仅是一种复原，基本上也可以确定非常接近清中期主流四川话的历史实际音系」。不知道是不是「宜」的讀音在清中期讀ni2，到了清末就轉變成了ngi2，最後在重慶話裡面轉變成了li2？還是《西蜀方言》紀錄有誤？

![宜](https://user-images.githubusercontent.com/22850071/164030791-6c90a3a9-b139-46c3-b133-fb656380c4f1.png)

**Comment by amorphobia** [comment]
应该是有「便宜 pian2 ni2」这个词的，见 #7

**Comment by amorphobia** [comment]
关于《西蜀方言》我隐约记得 QQ 群里我问过，大佬说这本书记录的是成都附近的方言，不能完全作为整个四川话通用拼音的依据

**Comment by AlienKevin** [comment]
我用重慶話打字的時候，pian2 ni2和pian2 li2都沒有給出便宜這個詞：

<img width="300" alt="Screen Shot 2022-04-19 at 21 50 56" src="https://user-images.githubusercontent.com/22850071/164130807-a61cdeaf-7fe6-4b12-92ab-fcff92a73c5a.png">

而且貌似重慶話裡面沒有ni這個發音，`shupin_congqin.schema.yaml`裡面有一條將所有開頭的ni都轉化成li的規則：
```
#泥來部分
    - xform/^ni/li/	#啓用此行表示ni, ni->li, li-
```

**Comment by amorphobia** [comment]
我删除自定义词库之后重新部署，打 pian li 能出「便宜」，应该是哪里配置的问题，你把你的 schema 贴出来看看吧

**Comment by AlienKevin** [comment]
<details>

<summary>

我`~/Library/Rime/shupin_congqin.schema.yaml`的內容

</summary>

```
# Rime schema
# encoding: utf-8

schema:
  schema_id: shupin_congqin
  name: 蜀拼-重慶
  version: "0.99"
  author:
    - Ciphotis <Keepout2010@163.com>
    - 涼風Papnas <Amridica.Commonwealth@protonmail.com>
    - 旷_野 <校對、詞彙增補>
    - soenghaagong<校對、詞彙增補>
    - holy19891004 <校對、詞彙增補>
  description: |
    「四川話通音」，以符號按鍵 - < \ / q 輸入五聲
  dependencies:
    - luna_pinyin

switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
#  - name: nippon
#    states: [ 傳統, 日本 ]
#    reset: 1
  - name: simplification
    states: [ 繁體, 简体 ]

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - r10n_translator
    - reverse_lookup_translator
    - "table_translator@english"
  filters:
    - simplifier
    - uniquifier

speller:
  alphabet: 'zyxwvutsrqponmlkjihgfedcba-;/<,>\'
  initials: zyxwvutsrqponmlkjihgfedcba
  delimiter: " '"
  algebra:

#顯示釋意註釋
    - xform/◎.+$//

#特字部分
    - xform/Ddi/le/	#的字讀音
    - xform/Dqu4/qie4/	#去字讀音
#    - xform/Dlu5/liu2/	#六字讀音
#    - xform/C//

#銳音un韻
    - derive/([dtlzcs])un/$1en/ #啓用此行表示dtlzcs+un都併入en

#通入部分
#    - xform/^([jqx])u5$/$1io5/	#啓用此行表示通入讀io
#    - xform/^([zcs])v5$/$1io5/	#啓用此行表示通入讀io
#    - xform/^([zcs])u5$/$1io5/	#啓用此行表示通入讀io
#    - xform/^yu5$/yo5/	#啓用此行表示通入讀io
    - xform/^([jqx])u5$/$1uu5/	#啓用此行表示通入讀üu
    - xform/^([zcs])v5$/$1vu5/	#啓用此行表示通入讀üu
    - xform/^([zcs])u5$/$1vu5/	#啓用此行表示通入讀üu
    - xform/^yu5$/yvu5/	#啓用此行表示通入讀üu
#    - xform/^([zcs])u5$/$1v5/	#啓用此行表示通入讀ü

#入聲派向部分
    - xform/5$/2/	#啓用此行表示入派陽平
#    - xform/5$/4/	#啓用此行表示入派去聲
#    - xform/5$/1/	#啓用此行表示入派陰平

#戈歌部分
    - xform/eo([1234])$/o$1/	#啓用此行表示不分舒聲戈歌
    - xform/eo5/o5/	#啓用此行表示不分入聲戈歌

#入聲部分（岷江適用）注意順序以及配合上方戈歌部分
#    - xform/ie5/i5/	#啓用此行表示ieq>iq
#    - xform/i5/ie5/	#啓用此行表示iq>ieq，注意和上行區分
#    - xform/([gkh])?e5/eo5/	#啓用此行表示喉音eq>eoq
#    - xform/ue5/o5/	#啓用此行表示ueq>oq
#    - xform/ve5/o5/	#啓用此行表示üeq>oq
#    - xform/e5/a5/	#啓用此行表示eq>aq
#    - xform/u5/o5/	#啓用此行表示uq>oq

#泥來部分
    - xform/^ni/li/	#啓用此行表示ni, ni->li, li-
    - xform/^nv/lv/
#    - xform/^ni/y/	#啓用此行表示ni->y-
#    - xform/^ni([12345])$/yi$1/	#啓用此行表示ni>yi

#尖團部分
    - xform/^zyi/ji/	#zyi>ji
    - xform/^cyi/qi/	#cyi>qi
    - xform/^syi/xi/	#syi>xi
    - xform/^zi([a-z]+)/ji$1/	#zi->ji-
    - xform/^ci([a-z]+)/qi$1/	#ci->qi-
    - xform/^si([a-z]+)/xi$1/	#si->xi-
    - xform/^zv/ju/	#zü>ju, zü->ju-
    - xform/^cv/qu/	#cü>qu, cü->qu-
    - xform/^sv/xu/	#sü>xu, sü->xu-
    - xform/^sv/xu/	#sü>xu, sü->xu-

    - xform/^yv/yu/ #yü>yu, yü->yu-

#平翹部分
    - xform/^([zcs])h/$1/   #啓用此行表示無翹舌

#h、f部分
    - xform/^hu([12345])$/fu$1/	#hu>fu
#    - xform/^hu([a-z]+)/f$1/	#hu->f-

    - xform/D//	#特字標記略去
    - derive/ngo([12345])/wo$1/	#「我」系列的略拼
    - abbrev/^([a-z]).+$/$1/	#首字母簡拼
    - derive/lve/lue/	#容許ve, ue在l後兩種拼寫
    - derive/^([jqxy])u/$1v/	#容許在jqxy後的u也可用v輸入
    - derive/([aeiou])ng/$1gn/	#誤拼容錯
    - derive/([iu])a(o|ng?)/a$1$2/	#誤拼容錯
    - derive/^([a-z]+)\d$/$1/	#可省略聲調輸入
    - 'xlit 12345 -<\/q'	#把碼表的數字替換爲可輸入的符號
    - 'derive/^(.*)-$/$1;/'	#-可以用;輸入
    - 'derive/^(.*)<$/$1,/'	#<可以用,輸入
    - 'derive/^(.*)\\$/$1>/'	#\可以用/輸入
    - derive/^(.*)q$/$1/	#q可以略去

translator:
  dictionary: shupin
  enable_charset_filter: true
  prism: shupin_congqin
  spelling_hints: 1  # 〜字以內候選標註完整帶調拼音
  preedit_format:
    - xform/◎.+$//
    - 'xform io[-;] iō'
    - 'xform io/ ió'
    - 'xform io[<,] iô'
    - 'xform io[>\\] iò'
    - 'xform ioq iǒ'
    - xform (u?|v?|i?)(eo|ui|iu|a|i|u|e|o|v)(i?|o?|u?|n?|ng?|r?)([-;/<,>\\q]) $1$2$4$3
    - 'xform a[-;] ā'
    - 'xform a/ á'
    - 'xform a[<,] â'
    - 'xform a[>\\] à'
    - 'xform aq ǎ'
    - 'xform e[-;] ē'
    - 'xform e/ é'
    - 'xform e[<,] ê'
    - 'xform e[>\\] è'
    - 'xform eq ě'
    - 'xform o[-;] ō'
    - 'xform o/ ó'
    - 'xform o[<,] ô'
    - 'xform o[>\\] ò'
    - 'xform oq ǒ'
    - 'xform i[-;] ī'
    - 'xform i/ í'
    - 'xform i[<,] î'
    - 'xform i[>\\] ì'
    - 'xform iq ǐ'
    - 'xform u[-;] ū'
    - 'xform u/ ú'
    - 'xform u[<,] û'
    - 'xform u[>\\] ù'
    - 'xform uq ǔ'
    - 'xform v[-;] ǖ'
    - 'xform v/ ǘ'
    - 'xform v[<,] ü̂'
    - 'xform v[>\\] ǜ'
    - 'xform vq ǚ'
    - 'xform v ü'
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/
  comment_format:
    #針對重慶音系
    - xform/Ddi/le/ #的字讀音
    - xform/Dqu4/qie4/  #去字讀音
    - derive/([dtlzcs])un/$1en/ #啓用此行表示dtlzcs+un都併入en
    - xform/^([jqx])u5($|(◎.+$))/$1uu5$2/  #啓用此行表示通入讀üu
    - xform/^([zcs])v5($|(◎.+$))/$1vu5$2/  #啓用此行表示通入讀üu
    - xform/^([zcs])u5($|(◎.+$))/$1vu5$2/  #啓用此行表示通入讀üu
    - xform/^yu5($|(◎.+$))/yvu5$1/ #啓用此行表示通入讀üu
    - xform/eo([1234])$/o$1/    #啓用此行表示不分舒聲戈歌
    - xform/eo5/o5/ #啓用此行表示不分入聲戈歌
    - xform/5($|(◎.+$))/2$1/   #啓用此行表示入派陽平
    - xform/^ni/li/ #啓用此行表示ni, ni->li, li-
    - xform/^nv/lv/
    - xform/^zyi/ji/    #zyi>ji
    - xform/^cyi/qi/    #cyi>qi
    - xform/^syi/xi/    #syi>xi
    - xform/^zi([a-z]+)/ji$1/   #zi->ji-
    - xform/^ci([a-z]+)/qi$1/   #ci->qi-
    - xform/^si([a-z]+)/xi$1/   #si->xi-
    - xform/^zv/ju/ #zü>ju, zü->ju-
    - xform/^cv/qu/ #cü>qu, cü->qu-
    - xform/^sv/xu/ #sü>xu, sü->xu-
    - xform/^sv/xu/ #sü>xu, sü->xu-
    - xform/^yv/yu/
    - xform/^([zcs])h/$1/   #啓用此行表示無翹舌
    - xform/^hu([12345])$/fu$1/ #hu>fu

    - xform/^(.*)$/〔$1〕
    - xform 了 liào
    - xform io1 iō
    - xform io4 ió
    - xform io2 iô
    - xform io3 iò
    - xform io5 iǒ
    - xform (u?|v?|i?)(eo|ui|iu|a|i|u|e|o|v)(i?|o?|u?|n?|ng?|r?)([1234q]) $1$2$4$3
    - xform/([nljqxyzcs])v/$1ü/
    - 'xform D '
    - xform a1 ā
    - xform a4 á
    - xform a2 â
    - xform a3 à
    - xform a5 ǎ
    - xform e1 ē
    - xform e4 é
    - xform e2 ê
    - xform e3 è
    - xform e5 ě
    - xform o1 ō
    - xform o4 ó
    - xform o2 ô
    - xform o3 ò
    - xform o5 ǒ
    - xform i1 ī
    - xform i4 í
    - xform i2 î
    - xform i3 ì
    - xform i5 ǐ
    - xform u1 ū
    - xform u4 ú
    - xform u2 û
    - xform u3 ù
    - xform u5 ǔ
    - xform ü1 ǖ
    - xform ü4 ǘ
    - xform ü2 ü̂
    - xform ü3 ǜ
    - xform ü5 ǚ
    - xform/([a-z]+)/$1/
    - xform/(◎.+)〕/〕$1/

reverse_lookup:
  dictionary: luna_pinyin
  prefix: "`"
  suffix: "'"
  tips: 〔拼音〕
  preedit_format:
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/
  comment_format:
    #針對重慶音系
    - xform/Ddi/le/ #的字讀音
    - xform/Dqu4/qie4/  #去字讀音
    - derive/([dtlzcs])un/$1en/ #啓用此行表示dtlzcs+un都併入en
    - xform/^([jqx])u5($|(◎.+$))/$1uu5$2/  #啓用此行表示通入讀üu
    - xform/^([zcs])v5($|(◎.+$))/$1vu5$2/  #啓用此行表示通入讀üu
    - xform/^([zcs])u5($|(◎.+$))/$1vu5$2/  #啓用此行表示通入讀üu
    - xform/^yu5($|(◎.+$))/yvu5$1/ #啓用此行表示通入讀üu
    - xform/eo([1234])$/o$1/    #啓用此行表示不分舒聲戈歌
    - xform/eo5/o5/ #啓用此行表示不分入聲戈歌
    - xform/5($|(◎.+$))/2$1/   #啓用此行表示入派陽平
    - xform/^ni/li/ #啓用此行表示ni, ni->li, li-
    - xform/^nv/lv/
    - xform/^zyi/ji/    #zyi>ji
    - xform/^cyi/qi/    #cyi>qi
    - xform/^syi/xi/    #syi>xi
    - xform/^zi([a-z]+)/ji$1/   #zi->ji-
    - xform/^ci([a-z]+)/qi$1/   #ci->qi-
    - xform/^si([a-z]+)/xi$1/   #si->xi-
    - xform/^zv/ju/ #zü>ju, zü->ju-
    - xform/^cv/qu/ #cü>qu, cü->qu-
    - xform/^sv/xu/ #sü>xu, sü->xu-
    - xform/^sv/xu/ #sü>xu, sü->xu-
    - xform/^yv/yu/
    - xform/^([zcs])h/$1/   #啓用此行表示無翹舌
    - xform/^hu([12345])$/fu$1/ #hu>fu

    - xform/^(.*)$/〔$1〕
    - xform ([aeiouv])(ng?|r)([1234q]) $1$3$2
    - xform ([aeo])([iuo])([1234q]) $1$3$2
    - xform/([nljqxyzcs])v/$1ü/
    - 'xform D '
    - xform a1 ā
    - xform a4 á
    - xform a2 â
    - xform a3 à
    - xform a5 ǎ
    - xform e1 ē
    - xform e4 é
    - xform e2 ê
    - xform e3 è
    - xform e5 ě
    - xform o1 ō
    - xform o4 ó
    - xform o2 ô
    - xform o3 ò
    - xform o5 ǒ
    - xform i1 ī
    - xform i4 í
    - xform i2 î
    - xform i3 ì
    - xform i5 ǐ
    - xform u1 ū
    - xform u4 ú
    - xform u2 û
    - xform u3 ù
    - xform u5 ǔ
    - xform ü1 ǖ
    - xform ü4 ǘ
    - xform ü2 ü̂
    - xform ü3 ǜ
    - xform ü5 ǚ
    - xform/([a-z]+)/$1/
    - xform/(◎.+)〕/〕$1/
  
punctuator:
  import_preset: default

key_binder:
  import_preset: default
  bindings:
    - { when: has_menu, accept: minus, send: minus }  # tone 1
    - { when: paging, accept: minus, send: Page_Up }

recognizer:
  import_preset: default
  patterns:
    reverse_lookup: "`[a-z]*'?$"

style:
  font_face: "微软雅黑"
  
english:
  dictionary: easy_en
  enable_completion: true
  enable_sentence: false
  initial_quality: "-1"
  spelling_hints: 9

#simplifier:
#  opencc_config: nippon.ini
#  option_name: nippon
#  tip: all
```

</details>
